DROP DATABASE IF EXISTS issuementor;
CREATE DATABASE IF NOT EXISTS issuementor;
USE issuementor;

SET GLOBAL time_zone = 'Europe/Madrid';

CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    birth_date DATE,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    login_date TIMESTAMP,
    role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
    gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT FALSE
);
