DROP DATABASE IF EXISTS issuementor;
CREATE DATABASE IF NOT EXISTS issuementor;
USE issuementor;

CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    birth_date DATE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    login_date TIMESTAMP,
    role ENUM('USER', 'ADMIN', 'TECHNICIAN') DEFAULT 'USER',
    gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    verified BOOLEAN DEFAULT FALSE
);
